version: '3.9'
services:
  db:
    image: postgres:16
    container_name: banco_de_dados_node
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meu_banco  # Adicionei um nome para o banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Nomeei o volume explicitamente
volumes:
  postgres_data:  # Definição explícita do volume
